---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)-20s%(levelname)-8s%(message)s"
    extended: 
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: extended
        stream: ext://sys.stderr
    mplog:
        class: raspyre_rpcserver.mplog.MultiProcessingLog
        level: INFO
        formatter: extended
        name: "rpc_server.log"
        mode: "a"
        maxsize: 1024
        rotate: 0
root:
    level: DEBUG
    handlers: [console, mplog]
#    handlers: [console]
#    handlers: [mplog]

